repos:
  - repo: local
    hooks:
      - id: go-version
        name: go version
        entry: scripts/check-go-version
        language: script
        types: [go]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: git://github.com/golangci/golangci-lint
    rev: v1.42.1
    hooks:
      - id: golangci-lint
        entry: bash -c 'exec golangci-lint run ${GOLANGCI_LINT_VERBOSE} -j=${GOLANGCI_LINT_CONCURRENCY:-1}' # custom bash so we can override concurrency for faster dev runs

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [-x]

  - repo: local
    hooks:
      - id: gomod
        name: gomod
        entry: scripts/pre-commit-go-mod
        language: script
        files: go.mod
        pass_filenames: false

  - repo: git://github.com/trussworks/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: markdown-toc

  - repo: local
    hooks:
      - id: scripts-docs
        name: scripts are documented
        entry: scripts/find-scripts-missing-in-readme
        language: script
        pass_filenames: false
