- id: ato-go-linter
  name: ato-go-linter
  description: Lint go files for ATO annotations
#  entry: go run ./cmd/ato/main.go -- ./...
#  language: golang
  entry: ./main
  language: script
  files: \.go$
